### ISSUE TITLE
Issue with hashrate display

### ISSUE THREAD

**Issue by MoneroCrusher** [easycryptomining/ecmgui#1]
![ecm](https://user-images.githubusercontent.com/32360383/40881682-3ba23916-66cd-11e8-959a-bb0ab19bd9d3.png)
![hashrate](https://user-images.githubusercontent.com/32360383/40881683-3bd67352-66cd-11e8-9b02-22247cd2b00c.png)

Hi there,

Thanks for the free tool!
There is little description though, so it might be hard for a linux noob to get everything working. I fought a long time for nginx to execute the php script correctly. Now that I've got it working, it doesn't display any hashrate or temperatures. For Rig IP I use 127.0.0.1:444 (when I try the command "wget 127.0.0.1:444" it shows all the hashrate tables correctly. Yes, I installed the server on the same machine as the miner, should be no Problem, right? Yet ECM can't read it.

Can you help me?
can you maybe leave your discord or telegram in here?

**Comment by easycryptomining** [comment]
Hello,

I'm having the same issue and it's because of nanopool api which don't send machine list the first (or even second, etc...) time. If you refresh multiple time you'll finished to have the table.

I'm planning to change lots of thing in the tools including an embedeed nginx. I'll give an update here when i'll have time to dev.

**Comment by MoneroCrusher** [comment]
Hi,
Thanks for the feedback.
I didn't give my nano miner a worker name, so if I put one, temp, uptime and hashes will appear? (I need them locally though from xmr-stak httpd port, not from nano)
Can you suggest a change of code that wouldn't require nano API? I just want to check local hashes, uptime and temperature and maybe I want to implement a raspberry Pi/Arduino to be able to turn off/on rig. Usually I mine to supportxmr.com.
Instead of nano "worker" maybe change it to local IP? 192.168.1.....
Would be glad if you could get back to me in chat, also wrote you a mail.

Thank you!
MoneroCrusher

**Comment by easycryptomining** [comment]
Hi,
I'm currently working on the next version which will have a configuration area and will not be dependent from a particular pool.

The current version ONLY work with nanopool as it retrieve the rig name from it, and THEN ask for hashrate, uptime, etc...

I don't respond in chat so that anybody can see the questions/answers.

If you want a really quick workaround :
In template\default\monero.php
- Comment from line 10 to 29
- Comment line 43 and 45
- Line 46 add an php array with your rigs hostname, for example : $machines= array('machine1', 'machine2');
- line 49 replace with $hostname = $machine;
- line 59 replace with $lastShare = time();

--> not tested but should do the tricks before i'll finished the next version.

**Comment by MoneroCrusher** [comment]
Thanks a lot for such a detailed answer and a potential fix (will try in a couple hours).
Also a question about SSH:
There's a folder /ecmgui/SSH with a text file
Am I supposed to put keys IN that text file or am I supposed to make a file with ssh key as name for each key? How would I go about having multiple SSH connections? 
Could you please make me an example how I would fill this out between Host A and Miner A, B, C..?
SSH
$sshUser = "[yourUserName]";
$sshKeyPub = "[absolutePath]/ssh/id_rsa.pub";
$sshKeyPriv = "[absolutePath]/ssh/id_rsa";

**Comment by MoneroCrusher** [comment]
Could you help me out with that?

**Comment by easycryptomining** [comment]
Hello,

You're supposed to put private and public key in the folder (not in the text file).
You can't have multiple ssh key as for me there is not point of doing this (one key to connect to multiple host, not one key for each host).

[yourUserName] = the name of the system user to use for ssh, ex : when you do "ssh [yourUserName]@minerA" --> the user that run your mining software
[absolutePath] = where you install ECMGUI web pages, ex : /var/www/html/ecmgui/ssh/....

--> this for creating ssh key : https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-on-ubuntu-1604

**Comment by easycryptomining** [comment]
Hi,

I've just push the new version of ECMGUI, which will solved most of your problems.

I close this issue.

Have fun ;)
